// Tables

Table departments {
  id int [pk, increment]
  name varchar [not null]
}

Table degree_programs {
  id int [pk, increment]
  name varchar [not null]
  department_id int [not null]
}

Table courses {
  id int [pk, increment]
  name varchar [not null]
  degree_program_id int [not null]
}

Table teachers {
  id int [pk, increment]
  name varchar [not null]
}

Table students {
  id int [pk, increment]
  name varchar [not null]
  degree_program_id int [not null]
}

Table exam_sessions {
  id int [pk, increment]
  date date [not null]
  course_id int [not null]
}

// Junction Tables

Table courses_teachers {
  teacher_id int [not null]
  course_id int [not null]

  indexes {
    (teacher_id, course_id) [pk]
  }
}

Table exam_session_registrations {
  student_id int [not null]
  exam_session_id int [not null]
  grade int [null]

  indexes {
    (student_id, exam_session_id) [pk]
  }
}

// Relationships

Ref: degree_programs.department_id > departments.id
Ref: courses.degree_program_id > degree_programs.id
Ref: students.degree_program_id > degree_programs.id
Ref: exam_sessions.course_id > courses.id

Ref: courses_teachers.teacher_id > teachers.id
Ref: courses_teachers.course_id > courses.id

Ref: exam_session_registrations.student_id > students.id
Ref: exam_session_registrations.exam_session_id > exam_sessions.id
